CREATE TABLE USERS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(50) UNIQUE,
  EMAIL VARCHAR(100),
  DPASSWORD CHAR(40)
);

INSERT INTO USERS (USERNAME, EMAIL, DPASSWORD) VALUES ('Вася', 'vasya@na.com', '12345');